// vue-todolist/src/components/TodoItem.vue
<template>
  <article>
    <p>{{TodoAttribut.item}}</p>
    <button @click="deleteItem()">-</button>
  </article>
</template>

<script>
export default {
  name: "to-do-item",
  props: ["TodoAttribut"],
  methods: {
    deleteItem() {
      this.$emit("delete");
    }
  }
};
</script>

<style scoped>
</style>

// angular-todolist/src/app/components/todoitem/todoitem.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Todo } from '../../models/todo';

@Component({
  selector: 'app-todoitem',
  templateUrl: './todoitem.component.html',
  styleUrls: ['./todoitem.component.css']
})
export class TodoitemComponent implements OnInit {
  @Input() todoAttribut: Todo;
  @Output() delete: EventEmitter<any> = new EventEmitter();
  constructor() {}
  deleteItem() {
    this.delete.emit();
  }
  ngOnInit() {}
}

<article>
  <p>{{ todoAttribut.item }}</p>
  <button (click)="deleteItem()">-</button>
</article>
