// angular-todolist/src/app/todolist/todolist.component.ts
import { Component, OnInit } from '@angular/core';
import { Todo } from '../models/todo';

@Component({
  selector: 'app-todolist',
  templateUrl: './todolist.component.html',
  styleUrls: ['./todolist.component.css']
})
export class TodolistComponent implements OnInit {
  list: Todo[] = [
    {
      id: 1,
      item: 'clean the house'
    },
    {
      id: 2,
      item: 'buy milk'
    }
  ];
  todo: Todo = { id: 0, item: '' };
  constructor() {}

  ngOnInit() {}
  createNewToDoItem() {
    // validate todo
    if (!this.todo) {
      alert('Please enter a todo!');
      return;
    }
    // Add the todo to the list
    const newId = Math.max.apply(null, this.list.map(t => t.id)) + 1;
    this.list.push({ id: newId, item: this.todo.item });
    this.todo.item = '';
  }
  onDeleteItem(todo) {
    this.list = this.list.filter(el => el !== todo);
  }
}

<main id="app">
  <img
    height="100"
    alt="Angular Logo"
    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
  />
  <h1>Angular Todo List</h1>
  <section>
    <div *ngFor="let todoElement of list">
      <app-todoitem
        [todoAttribut]="todoElement"
        (delete)="onDeleteItem(todoElement)"
      ></app-todoitem>
    </div>
  </section>

  <!-- Usually, every input should be inside a form -->
  <section>
    <input type="text" [(ngModel)]="todo.item" (keyup.enter)="createNewToDoItem()" />
    <button (click)="createNewToDoItem()">+</button>
  </section>
</main>

// vue-todolist/src/TodoList.vue
<template>
  <main id="app">
    <img :src="logo" alt="Vue logo">
    <h1>Vue Todo List</h1>
    <section>
      <TodoItem
        v-for="todoElement of list"
        :key="todoElement.id"
        :TodoAttribut="todoElement"
        @delete="onDeleteItem(todoElement)"
      />
    </section>
    <section>
      <input type="text" v-model="todo" v-on:keyup.enter="createNewToDoItem">
      <button @click="createNewToDoItem()">+</button>
    </section>
  </main>
</template>

<script>
import TodoItem from "./components/TodoItem.vue";
import Logo from "./assets/logo.png";
export default {
  name: "to-do",
  components: {
    TodoItem
  },
  data() {
    return {
      list: [
        {
          id: 1,
          item: "clean the house"
        },
        {
          id: 2,
          item: "buy milk"
        }
      ],
      todo: "",
      logo: Logo
    };
  },
  methods: {
    createNewToDoItem() {
      //validate todo
      if (!this.todo) {
        alert("Please enter a todo!");
        return;
      }
      //Add the todo to the list
      const newId = Math.max.apply(null, this.list.map(t => t.id)) + 1;
      this.list.push({ id: newId, item: this.todo });
      this.todo = "";
    },
    onDeleteItem(todo) {
      this.list = this.list.filter(el => el !== todo);
    }
  }
};
</script>

<style>
</style>
